version: "3"                                                                                          
services:

  rocky9a:
    build: .
    container_name: rocky9a
    hostname: rocky9a
    restart: always
    privileged: true
    #ports:
    #  - "5432:5432"
    #volumes:
    #  - ./volume/home:/home
    tty: true
    command: >
      bash -c "/sbin/init"
    environment:
      TZ: Asia/Tokyo
